### ISSUE TITLE
Mouse clicks are not registered on MacOS

### ISSUE THREAD

**Issue by JelleDamen** [prime31/Nez-Samples#9]
I've tried building with Visual Studio for mac and Xamarin Studio. In both the app does start but I'm not able to click on the buttons to switch between the sample's.

On the base class (SampleScene) the onToggleSceneListClicked is not getting fired. Any suggestions ?

**Comment by prime31** [comment]
MonoGame 3.5 is basically totally broken with regard to mouse input and screen size (you'll notice it is very tiny/half sized) on retina Macs. If you move the window into the top/left corner of the screen and move your mouse to the center of the screen you can actually click the buttons. Do note that click + drag is completely broken though so that wont work. This is all fixed in MonoGame 3.6.
